ci:
  autoupdate_commit_msg: "chore: [pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: "monthly"
  autoupdate_branch: "dev"

repos:
  # --- Generic hygiene --------------------------------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # --- Python formatting & linting -------------------------------------------
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.0
    hooks:
      - id: pyupgrade
        # set your minimum supported Python here
        args: ["--py311-plus"]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.9.0
    hooks:
      - id: black
        args: ['--config=./pyproject.toml']
  - repo: https://github.com/pycqa/isort
    rev: '7.0.0'
    hooks:
      - id: isort
        args: ['--settings-path=./pyproject.toml']
  # --- C++ formatting & analysis ---------------------------------------------
  - repo: local
    hooks:
      - id: generate-headers
        name: generate headers
        files: ^instruction_set.yaml$
        entry: python generate_headers.py
        language: python
        additional_dependencies: [pyyaml]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v21.1.6'
    hooks:
      - id: clang-format
        types_or: [c++, c, cuda]
